version: "3"

services:
  portainer:
    image: portainer/portainer
    restart: always
    command: --no-auth
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data portainer/portainer
    networks:
      - portainer-ntw

  watchtower:
    image: v2tec/watchtower
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - portainer-ntw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  portainer-ntw:
    driver: bridge
