# https://portainer.readthedocs.io/en/stable/agent.html

version: "3.2"

services:
  portainer:
    image: portainer/portainer
    command: --no-auth
    ports:
      - target: 9000
        published: 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data portainer/portainer
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - portainer_agent_network

  watchtower:
    image: v2tec/watchtower
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_agent_network


networks:
  portainer_agent_network:
    driver: overlay
    attachable: true
